[package]
name = "soundkit-aac"
version = "0.1.0"
edition = "2021"

[dependencies]
fdk-aac = { git = "https://github.com/wavey-ai/fdk-aac-rs.git" }
soundkit = { git = "https://github.com/wavey-ai/soundkit.git" }
tracing = "0.1.40"
